apiVersion: eda.ansible.com/v1alpha1
kind: EDA
metadata:
  name: eda
  namespace: eda
spec:
  automation_server_url: https://ansible_aap_controller 
  service_type: nodeport
  automation_server_ssl_verify: "false"
  no_log: false  

