apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/ansible/eda-server-operator/config/default

images:
  - name: quay.io/philip860/eda-server-operator
    newTag: fix-nginx-not-redirecting-to-eda-login-page

# Specify a custom namespace in which to install EDA
namespace: eda
