---
- name: Configure EDA Standalone Server
  hosts: "{{ eda_single_node }}" 
  gather_facts: true
  become: true
  #Comment out vars_prompt entries to run playbook manually
  vars_prompt:


    - name: eda_single_node
      prompt: "Please enter a name for sever to run awx install playbook on"
      private: no 

    # - name: eda_postgres_db_password
    #   prompt: "What is the Password for AWX Postgres DB?"
    #   private: no 

    # - name: secret_key
    #   prompt: "Please enter a secret key to use for Postgres DB encryption"
    #   private: no 

    # - name: eda_admin_username
    #   prompt: "What is the name of the AWX Admin User?"
    #   private: no 

    # - name: eda_admin_username_password
    #   prompt: "What is the password for the AWX Admin User?"
    #   private: no 

    - name: eda_user_password_var
      prompt: "Enter a password for local awx user to be created on system"
      private: no 


    - name: ansible_aap_controller
      prompt: "Enter the hostname of the Ansible AAP/AWX Controller Server"
      private: no  

  roles:
  
    - install_required_packages
    - install_k3s
    - generate_self_signed_tls_certs_for_awx_server
    - eda_operator_setup
    - configure_standalone_eda_server
    # - configure_eda_server_proxy
    #- wait_for_pods_to_initialize
