


- name: Copy Self Generate SSL Cert To /etc/nginx/certs directory
  ansible.builtin.shell: cp -r /admin_tools/eda-operator/eda-deploy/tls.crt  /etc/nginx/certs/server.crt
  args:
    executable: /bin/bash


- name: Copy Self Generate SSL Private Key To /etc/nginx/certs directory
  ansible.builtin.shell: cp -r /admin_tools/eda-operator/eda-deploy/tls.key  /etc/nginx/certs/server.key
  args:
    executable: /bin/bash


############################




- name: Get AWX service NodePort
  ansible.builtin.shell: "kubectl get service eda-service -n awx -o jsonpath='{.spec.ports[0].nodePort}'"
  args:
    executable: /bin/bash
  register: eda_service_output

- name: Print extracted service port
  ansible.builtin.debug:
     msg: "Extracted service port is {{ eda_service_output.stdout }}"


- name: Set eda_service_port variable
  set_fact:
    eda_service_port: "{{ eda_service_output.stdout }}"




- name: Copy Over Custom Nginx config_files to /etc/nginx/sites-available/eda-ssl.conf
  ansible.builtin.template:
    src: "{{ role_path }}/files/eda-ssl.conf"
    dest: "/etc/nginx/sites-available/eda-ssl.conf"


- name: Set symbolic link for /etc/nginx/sites-available/
  ansible.builtin.shell: "ln -s /etc/nginx/sites-available/eda-ssl.conf /etc/nginx/sites-enabled/"
  args:
    executable: /bin/bash


- name: Copy Over Custom eda-no-ssl-ubuntu.conf Nginx file to /etc/nginx/sites-available/default
  ansible.builtin.copy:
    src: "{{ role_path }}/files/eda-no-ssl-ubuntu.conf"
    dest: "/etc/nginx/sites-available/default"





- name: Restart Nginx
  service:
    name: nginx
    state: restarted





  



