

- name: Copy Self Generate SSL Cert To /etc/nginx/certs directory
  ansible.builtin.shell: cp -r /admin_tools/awx-operator/awx-deploy/tls.crt  /etc/nginx/certs/server.crt
  args:
    executable: /bin/bash


- name: Copy Self Generate SSL Private Key To /etc/nginx/certs directory
  ansible.builtin.shell: cp -r /admin_tools/awx-operator/awx-deploy/tls.key  /etc/nginx/certs/server.key
  args:
    executable: /bin/bash


############################




- name: Get AWX service NodePort
  ansible.builtin.shell: "kubectl get service awx-service -n awx -o jsonpath='{.spec.ports[0].nodePort}'"
  args:
    executable: /bin/bash
  register: awx_service_output

- name: Print extracted service port
  ansible.builtin.debug:
     msg: "Extracted service port is {{ awx_service_output.stdout }}"


- name: Set awx_service_port variable
  set_fact:
    awx_service_port: "{{ awx_service_output.stdout }}"




- name: Copy Over Custom Nginx config_files to /etc/nginx/conf.d/awx-ssl.conf
  ansible.builtin.template:
    src: "{{ role_path }}/files/awx-ssl.conf"
    dest: "/etc/nginx/conf.d/awx-ssl.conf"


- name: Copy Over Custom Nginx config_files to /etc/nginx/conf.d/awx-no-ssl.conf
  ansible.builtin.copy:
    src: "{{ role_path }}/files/awx-no-ssl.conf"
    dest: "/etc/nginx/conf.d/awx-no-ssl.conf"


- name: Set Nginx SELinux Rule
  ansible.builtin.shell: "setsebool -P httpd_can_network_connect 1"
  args:
    executable: /bin/bash




- name: Restart Nginx
  service:
    name: nginx
    state: restarted





  



