---



- name: Create the /admin_tools/eda_awx_install_config/quay_io_repo_images Directory if it is not present
  ansible.builtin.file:
    path: "/admin_tools/eda_awx_install_config/quay_io_repo_images"
    state: directory
    mode: '0755'
    recurse: yes



- name: Pull the quay.io eda Images That Are Working
  ansible.builtin.shell: "podman pull quay.io/philip860/{{ item }}"
  args:
    chdir:
    executable: /bin /bin/bash
  loop:
    - eda-server-operator:main
    - eda-server:main
    - eda-ui:main
    - postgresql-15-c9s:latest
    - redis-6-c9s:c9s


